# Generated by Django 4.1.2 on 2022-10-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=400)),
                ('field', models.FileField(max_length=254, upload_to=None)),
            ],
            options={
                'verbose_name': 'jurisp',
                'verbose_name_plural': 'jurisps',
            },
        ),
    ]
