# Generated by Django 4.1.2 on 2022-10-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisp',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Jurisp'),
        ),
    ]
