# Generated by Django 4.1.2 on 2022-10-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisp', '0002_jurisp_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurisp',
            name='imagen',
        ),
        migrations.AddField(
            model_name='jurisp',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jurisp',
            name='field',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=None),
        ),
    ]
