# Generated by Django 4.1.2 on 2022-10-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Links',
        ),
    ]
